import { BellRing, Check, ChevronRight, LockKeyhole, Save, SlidersHorizontal, UserRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { PageHeader } from '@/components/ui-kit';

function Toggle({ label, detail, value, onChange, testId }: { label: string; detail: string; value: boolean; onChange: (value: boolean) => void; testId: string }) {
  return <button data-testid={testId} onClick={() => onChange(!value)} className="cg-focus flex w-full items-center justify-between gap-4 py-4 text-left"><div><div className="text-[12px] font-bold">{label}</div><div className="mt-1 text-[10px] leading-relaxed text-muted-foreground">{detail}</div></div><span className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${value ? 'bg-primary' : 'bg-muted'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-card shadow-sm transition-transform ${value ? 'translate-x-6' : 'translate-x-1'}`} /></span></button>;
}

export default function Settings() {
  const [name, setName] = useState('Avery Mitchell');
  const [workspace, setWorkspace] = useState('Northstar Studio');
  const [email, setEmail] = useState('avery@northstar.studio');
  const [notifications, setNotifications] = useState(true);
  const [digest, setDigest] = useState(false);
  const [saved, setSaved] = useState(false);
  const save = (event: FormEvent) => { event.preventDefault(); setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <div className="cg-page mx-auto max-w-[980px]"><PageHeader eyebrow="Workspace controls" title="Settings" description="Tune how CyberGuard works for you and Northstar Studio." />
    <form onSubmit={save} className="space-y-4"><section className="cg-panel overflow-hidden"><div className="flex items-center gap-3 border-b border-border px-5 py-4"><UserRound size={16} className="text-primary" /><div><div className="cg-kicker">Identity</div><h2 className="mt-1 text-[14px] font-extrabold">Account and workspace</h2></div></div><div className="grid gap-5 p-5 md:grid-cols-2 md:p-6"><label className="space-y-2"><span className="cg-kicker block">Your name</span><input data-testid="input-account-name" value={name} onChange={(event) => setName(event.target.value)} className="cg-input" /></label><label className="space-y-2"><span className="cg-kicker block">Workspace name</span><input data-testid="input-workspace-name" value={workspace} onChange={(event) => setWorkspace(event.target.value)} className="cg-input" /></label><label className="space-y-2 md:col-span-2"><span className="cg-kicker block">Notification email</span><input data-testid="input-notification-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="cg-input" /></label></div></section>
      <section className="cg-panel divide-y divide-border overflow-hidden px-5"><div className="flex items-center gap-3 py-4"><BellRing size={16} className="text-primary" /><div><div className="cg-kicker">Signal delivery</div><h2 className="mt-1 text-[14px] font-extrabold">When CyberGuard should speak up</h2></div></div><Toggle label="Critical alert notifications" detail="Receive an email when a critical signal is detected." value={notifications} onChange={setNotifications} testId="button-toggle-critical-notifications" /><Toggle label="Weekly posture digest" detail="A compact summary of score movement and open alerts." value={digest} onChange={setDigest} testId="button-toggle-weekly-digest" /></section>
      <section className="cg-panel overflow-hidden"><div className="flex items-center gap-3 border-b border-border px-5 py-4"><SlidersHorizontal size={16} className="text-primary" /><div><div className="cg-kicker">Analysis defaults</div><h2 className="mt-1 text-[14px] font-extrabold">Defensive preferences</h2></div></div><div className="divide-y divide-border"><button type="button" data-testid="button-preference-data-retention" onClick={() => setSaved(true)} className="flex w-full items-center justify-between px-5 py-4 text-left hover:bg-muted/30"><div><div className="text-[12px] font-bold">Analysis data retention</div><div className="mt-1 text-[10px] text-muted-foreground">Keep results available for 30 days</div></div><div className="flex items-center gap-2 text-[11px] font-bold text-muted-foreground">30 days<ChevronRight size={14} /></div></button><button type="button" data-testid="button-preference-confirmation" onClick={() => setSaved(true)} className="flex w-full items-center justify-between px-5 py-4 text-left hover:bg-muted/30"><div><div className="text-[12px] font-bold">Scan confirmation</div><div className="mt-1 text-[10px] text-muted-foreground">Ask before submitting external content</div></div><div className="flex items-center gap-2 text-[11px] font-bold text-primary">On<ChevronRight size={14} /></div></button></div></section>
      <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-[11px] text-muted-foreground"><LockKeyhole size={13} />Workspace controls are private to your account.</div><button data-testid="button-save-settings" type="submit" className="cg-btn cg-btn-primary">{saved ? <Check size={14} /> : <Save size={14} />}{saved ? 'Saved' : 'Save changes'}</button></div>
    </form>
  </div>;
}